# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Checkout selenium tests repository
      uses: actions/checkout@v2
      with:
        repository: mmravi99/BisCred.git
        ref: main
        path: ./
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Selenium tests
      run: |
          ls -l
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: "mmravi99@gmail.com"
        password: "abcd@1234"
    - name: Run Docker container
      run: |
        docker run -d --name my_container -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:4.21.0-20240522
